export const EVENT_INFO = 'Event Info'
export const SEARCH = 'View Events'
export const EMAIL = 'Email'
export const ABOUT_MEDSCAPE_LIVE = `About MedscapeLIVE!`
export const CONTACT_US = `Contact Us`
export const ABOUT = `About`
export const HOME = `Home`
export const EVENTS = `Events`
export const VIEW_ALL_EVENTS = 'View All Events'
export const ALL_SPECIALTIES = 'Specialty'
export const ALL_LOCATIONS = 'Location/Virtual'
export const ANY_DATES = 'Any dates'
export const FROM = 'From'
export const TO = 'To'
export const SPECIALTY = 'Specialty'
export const LOCATION = 'Location'
export const ACCREDITED = 'Accredited'
export const LIVENOW = 'LIVE NOW'
export const REGISTER = 'Register'
export const MEDSCAPE_LOGO_ALT = 'Medscape Logo'
export const HOME_SEARCH_BACKGROUND_ALT = 'Home Search Background Image'
export const MEDSCAPE_LIVE_LOGO_ALT = 'MedscapeLive! Logo'
export const HERO_HEADER_BACKGROUND_ALT = 'Hero Header Background Image'
export const DROP_DOWN_INDICATOR_ALT = 'Dropdown indicator'
export const RIGHT_INDICATOR_ALT = 'Right arrow indicator'
export const LEFT_INDICATOR_ALT = 'Left arrow indicator'
export const USER_NOT_FOUND_ALT = 'User not found'
