export const startDateIso = 'startDateIso'
export const endDateIso = 'endDateIso'
export const dateError = 'dateError'
export const startDateDisplay = 'startDateDisplay'
export const endDateDisplay = 'endDateDisplay'
export const datesDisplay = 'datesDisplay'
export const minimumDate = 'minimumDate'
export const shouldDisableSearch = 'shouldDisableSearch'
export const getLiveEventsErrorMessage = 'getLiveEventsErrorMessage'
export const selectedSpecialtiesDisplay = 'selectedSpecialtiesDisplay'
export const selectedLocationsDisplay = 'selectedLocationsDisplay'
export const searchFiltersNetworkErrorMessage =
  'searchFiltersNetworkErrorMessage'
export const selectedSpecialtyLocations = 'selectedSpecialtyLocations'
